mf:
	git add Makefile
	git commit -m "Makefile"
	git push origin HEAD

ax:
	git add Axios.md
	git commit -m "How to install 'axios' to Vue CLI Project."
	git push origin HEAD

pro-wsl:
	git add MakeProjectForWSL2.md
	git commit -m "How to make a Vue CLI project for WSL2."